# NumPy

NumPy is used for working with arrays.

In [15]:
 # create a NumPy array 
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [16]:
#Create a 0-D array with value 1

arr = np.array(1)

print(arr)

1


In [17]:
#Create a 1-D array containing the values 1,2,3,4,5
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [18]:
#Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
#Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:
(layer,row,column)
arr3 = np.array([[[1,2,3],[4,5,6]],
                 [[1,2,3],[4,5,6]]])

arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [22]:
#Check how many dimensions the arrays have
#see the number of square brackets for dimensions
print(f"arr1 dimension : {arr1.ndim}")
print(f"arr2 dimension : {arr2.ndim}")
print(f"arr3 dimension : {arr3.ndim}")


arr1 dimension : 1
arr2 dimension : 2
arr3 dimension : 3


In [23]:
arr = np.array([1, 2, 3, 4], ndmin=2)
arr

array([[1, 2, 3, 4]])

In [34]:
#Access the element on the first row, second column:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])
print('5th element on 2nd row: ', arr[1, 4])
print("dimension", arr.ndim)

2nd element on 1st row:  2
5th element on 2nd row:  10
dimension 2


In [33]:
arr3 = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])

# Get the shape of the array
layers, rows, columns = arr3.shape

print("Number of layers:", layers)
print("Number of rows per layer:", rows)
print("Number of columns per row:", columns)
print("dimension", arr3.ndim)

Number of layers: 2
Number of rows per layer: 2
Number of columns per row: 3


In [30]:
arr3 = np.array([[[1,2,3]], [[4,5,6]],[[7,8,9]]])

# Get the shape of the array
layers, rows, columns = arr3.shape

print("Number of layers:", layers)
print("Number of rows per layer:", rows)
print("Number of columns per row:", columns)
print("dimension", arr3.ndim)

Number of layers: 3
Number of rows per layer: 1
Number of columns per row: 3


In [32]:
arr3 = np.array([[[1,2]], [[4,5]],[[7,8]]])

# Get the shape of the array
layers, rows, columns = arr3.shape

print("Number of layers:", layers)
print("Number of rows per layer:", rows)
print("Number of columns per row:", columns)
print("dimension", arr3.ndim)

Number of layers: 3
Number of rows per layer: 1
Number of columns per row: 2
dimension 3


In [38]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

"""in arr[0,1,2] : 0 is the first dimension means two arrays 
[1,2,3] [4,5,6]
 1 means the second array means [4,5,6]
 2 means the third elements in the array of [4,5,6] so ans is 6 """


6


'in arr[0,1,2] : 0 is the first dimension means two arrays \n[1,2,3] [4,5,6]\n 1 means the second array means [4,5,6]\n 2 means the third elements in the array of [4,5,6] so ans is 6 '

In [40]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

"""
from arr[1, -1] 1 is the second array [6,7,8,9,10] and -1 is the last index so ans is 10
"""

Last element from 2nd dim:  10


'\nfrom arr[1, -1] 1 is the second array [6,7,8,9,10] and -1 is the last index so ans is 10\n'

## Array slicing

In [42]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
# last index is not considered

[2 3 4 5]


In [43]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])
# from 4th index to the last index

[5 6 7]


In [44]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])
# from 0 index to 4-1 index

[1 2 3 4]


In [45]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])
# second argument of slicing is -1 which is not considered so ans in [5,6]

[5 6]


In [46]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])
# starting from index 1 upto index 5-1 step 2 so ans is [2,4]


[2 4]


In [50]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:])
#starting from 0th index upto including last index so ans is all elements

[1 2 3 4 5 6 7]


In [51]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::])
#starting from 0th index upto including last index with no step value  so ans is all elements

[1 2 3 4 5 6 7]


In [52]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])
#starting from 0th index to including last index with step value 2 so ans is [1,3.5,7]

[1 3 5 7]


In [53]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
# from 1 means second array [6,7,8,9,10] from 1 to index 4-1 so ans is [7,8,9]

[7 8 9]


In [58]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:1, 4])
#from only first array coz second is 1-1 not considered extract the 4th index so ans is [5]

[5]


In [60]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 4])
#from 0th array and from 2-1 = 1st array extract 4th index so ans is [5,10]

[ 5 10]


In [61]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])
# from 0th array and from 1st array extract the index from 1 to 4 so ans is [[2,3,4][7,8,9]]

[[2 3 4]
 [7 8 9]]


In [62]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr[1:4])

[15 20 25]
