### numpy Random

In [1]:
#Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

In [ ]:
#Random numbers generated through a generation algorithm are called pseudo random.

In [29]:
# Generate a random integer from 0 to 10
from numpy import random

x = random.randint(10)

print(x)

1


In [35]:
#The random module's rand() method returns a random float between 0 and 1.
from numpy import random

x = random.rand()

print(x)

0.37800048681941123


In [42]:
#Generate a 1-D array containing 5 random integers from 0 to 10
from numpy import random

x=random.randint(10, size=(5))

print(x)

[8 0 2 8 7]


In [43]:
#Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100
from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[93 83 54 13 57]
 [ 2 25 41 52 27]
 [33 64 74 33 65]]


In [51]:
#The choice() method allows you to generate a random value based on an array of values.
from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

7


In [52]:
from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[5 5 3 5 5 7 7 7 5 3 7 5 7 7 7 3 7 7 7 7 5 7 7 7 5 7 7 5 7 5 5 7 7 5 5 7 7
 3 5 5 5 7 7 5 7 3 7 7 3 7 7 7 7 7 3 7 7 7 7 3 7 7 7 7 5 7 3 5 5 5 7 7 5 7
 7 7 7 7 3 7 7 7 7 5 7 7 7 7 5 7 5 5 7 5 7 5 5 3 7 7]


In [56]:
#random permutation
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[5 4 1 3 2]


In [64]:
#Generate a random permutation of elements of following array:

from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))

[5 3 1 4 2]
