# NumPy

NumPy is used for working with arrays.

In [2]:
 # create a NumPy array 
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [16]:
#Create a 0-D array with value 1

arr = np.array(1)

print(arr)

1


In [17]:
#Create a 1-D array containing the values 1,2,3,4,5
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [18]:
#Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
#Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:
(layer,row,column)
arr3 = np.array([[[1,2,3],[4,5,6]],
                 [[1,2,3],[4,5,6]]])

arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [22]:
#Check how many dimensions the arrays have
#see the number of square brackets for dimensions
print(f"arr1 dimension : {arr1.ndim}")
print(f"arr2 dimension : {arr2.ndim}")
print(f"arr3 dimension : {arr3.ndim}")


arr1 dimension : 1
arr2 dimension : 2
arr3 dimension : 3


In [23]:
arr = np.array([1, 2, 3, 4], ndmin=2)
arr

array([[1, 2, 3, 4]])

In [34]:
#Access the element on the first row, second column:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])
print('5th element on 2nd row: ', arr[1, 4])
print("dimension", arr.ndim)

2nd element on 1st row:  2
5th element on 2nd row:  10
dimension 2


In [33]:
arr3 = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])

# Get the shape of the array
layers, rows, columns = arr3.shape

print("Number of layers:", layers)
print("Number of rows per layer:", rows)
print("Number of columns per row:", columns)
print("dimension", arr3.ndim)

Number of layers: 2
Number of rows per layer: 2
Number of columns per row: 3


In [30]:
arr3 = np.array([[[1,2,3]], [[4,5,6]],[[7,8,9]]])

# Get the shape of the array
layers, rows, columns = arr3.shape

print("Number of layers:", layers)
print("Number of rows per layer:", rows)
print("Number of columns per row:", columns)
print("dimension", arr3.ndim)

Number of layers: 3
Number of rows per layer: 1
Number of columns per row: 3


In [32]:
arr3 = np.array([[[1,2]], [[4,5]],[[7,8]]])

# Get the shape of the array
layers, rows, columns = arr3.shape

print("Number of layers:", layers)
print("Number of rows per layer:", rows)
print("Number of columns per row:", columns)
print("dimension", arr3.ndim)

Number of layers: 3
Number of rows per layer: 1
Number of columns per row: 2
dimension 3


In [38]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

"""in arr[0,1,2] : 0 is the first dimension means two arrays 
[1,2,3] [4,5,6]
 1 means the second array means [4,5,6]
 2 means the third elements in the array of [4,5,6] so ans is 6 """


6


'in arr[0,1,2] : 0 is the first dimension means two arrays \n[1,2,3] [4,5,6]\n 1 means the second array means [4,5,6]\n 2 means the third elements in the array of [4,5,6] so ans is 6 '

In [40]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

"""
from arr[1, -1] 1 is the second array [6,7,8,9,10] and -1 is the last index so ans is 10
"""

Last element from 2nd dim:  10


'\nfrom arr[1, -1] 1 is the second array [6,7,8,9,10] and -1 is the last index so ans is 10\n'

## Array slicing

In [42]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
# last index is not considered

[2 3 4 5]


In [43]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])
# from 4th index to the last index

[5 6 7]


In [44]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])
# from 0 index to 4-1 index

[1 2 3 4]


In [45]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])
# second argument of slicing is -1 which is not considered so ans in [5,6]

[5 6]


In [46]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])
# starting from index 1 upto index 5-1 step 2 so ans is [2,4]


[2 4]


In [50]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:])
#starting from 0th index upto including last index so ans is all elements

[1 2 3 4 5 6 7]


In [51]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::])
#starting from 0th index upto including last index with no step value  so ans is all elements

[1 2 3 4 5 6 7]


In [52]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])
#starting from 0th index to including last index with step value 2 so ans is [1,3.5,7]

[1 3 5 7]


In [53]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
# from 1 means second array [6,7,8,9,10] from 1 to index 4-1 so ans is [7,8,9]

[7 8 9]


In [58]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:1, 4])
#from only first array coz second is 1-1 not considered extract the 4th index so ans is [5]

[5]


In [60]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 4])
#from 0th array and from 2-1 = 1st array extract 4th index so ans is [5,10]

[ 5 10]


In [61]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])
# from 0th array and from 1st array extract the index from 1 to 4 so ans is [[2,3,4][7,8,9]]

[[2 3 4]
 [7 8 9]]


In [62]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr[1:4])

[15 20 25]


In [3]:
#Converting an array into a different datatype
arr = np.array([1.1, 2.1, 3.1])
print(arr)
print(arr.dtype)
newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)


[1.1 2.1 3.1]
float64
[1 2 3]
int32


In [4]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


## Difference between copy and view

#The view SHOULD be affected by the changes made to the original array.

#The copy SHOULD NOT be affected by the changes made to the original array.

## Copy

In [5]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [6]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [7]:
#The original array SHOULD be affected by the changes made to the view.
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


## Shape of array

In [8]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)
#The example above returns (2, 4), which means that the array has 2 dimensions, 
#where the first dimension has 2 elements and the second has 4

(2, 4)


In [13]:
arr = np.array([1, 2, 3, 4])

print(arr)
print('shape of array :', arr.shape)
layers, rows, columns = arr.shape
print("Number of layers:", layers)
print("Number of rows per layer:", rows)
print("Number of columns per row:", columns)
print("dimension", arr.ndim)

[1 2 3 4]
shape of array : (4,)


ValueError: not enough values to unpack (expected 3, got 1)

In [ ]:
print("Number of layers:", layers)
print("Number of rows per layer:", rows)
print("Number of columns per row:", columns)
print("dimension", arr3.ndim)

## Array Iterating

In [14]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


## nditer

In [17]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [18]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)


1
3
5
7


### concatenate

In [19]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [23]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=0)

print(arr)
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [24]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [25]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


### Split

In [33]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [34]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [35]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


### Searching Arrays

In [36]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [37]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [38]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [39]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [40]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [41]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [42]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [43]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


## Filter

In [44]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [45]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [46]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [47]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
